### ISSUE TITLE
Invariant Violation: "//" is not a valid style property.

### ISSUE THREAD

**Issue by Zn4rK** [styled-components/css-to-react-native#133]
```ts
styled.View`
  // background: green;
  background: red;
`;
```

Yields:
```
Invariant Violation: "//" is not a valid style property.
StyleSheet generated: {
  "//": "green",
  "backgroundColor": "red"
}
Valid style props: [
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
   ...etc
]
```

StackTrace:
```
 at invariant (node_modules/invariant/invariant.js:40:15)
    at styleError (node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:77:3)
    at Function.validateStyleProp (node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:35:7)
    at Function.validateStyle (node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:55:28)
    at Object.create (node_modules/react-native/Libraries/StyleSheet/StyleSheet.js:355:30)
    at InlineStyle.generateStyleObject (node_modules/styled-components/native/dist/styled-components.native.cjs.js:5809:33)
    at StyledNativeComponent.generateAndInjectStyles (node_modules/styled-components/native/dist/styled-components.native.cjs.js:6037:24)
    at node_modules/styled-components/native/dist/styled-components.native.cjs.js:5991:36
    at updateContextConsumer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9740:19)
    at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10123:14)
```

Relevant dependencies:
```
    "styled-components": "^5.0.1"
    "react-native": "^0.61.5",
    "react-test-renderer": "^16.12.0",
```

**Comment by Zn4rK** [comment]
Closing this and opening in styled-components/styled-components instead. Feel free to reopen if it should be handled here.

**Comment by Zn4rK** [comment]
Would it make sense to handle parsing of comments in this repository? I opened a PR with a failing test in styled-components - but @kitten thought it should be handled here.

**Comment by jacobp100** [comment]
Have a look at the API for this project - we only parse individual CSS properties and values as strings

To support this, it would need to be done at the CSS parser level. Also note that `//` comments aren't valid CSS, so you'd need a CSS parser that adds support for them

**Comment by Zn4rK** [comment]
Cool! I agree - just wanted to make sure :)
