### ISSUE TITLE
Provide support for variable currentColor

### ISSUE THREAD

**Issue by fortezhuo** [styled-components/css-to-react-native#143]
```
/Users/forte/Workspace/freedom/node_modules/css-to-react-native/index.js:825
    throw new Error("Failed to parse declaration \"" + propName + ": " + value + "\"");
    ^

Error: Failed to parse declaration "borderColor: currentColor"
    at transformShorthandValue (/Users/forte/Workspace/freedom/node_modules/css-to-react-native/index.js:825:11)
    at getStylesForProperty (/Users/forte/Workspace/freedom/node_modules/css-to-react-native/index.js:834:109)
    at /Users/forte/Workspace/freedom/node_modules/css-to-react-native/index.js:857:33
    at Array.reduce (<anonymous>)
    at index (/Users/forte/Workspace/freedom/node_modules/css-to-react-native/index.js:853:16)
    at getStyles (/Users/forte/Workspace/freedom/client/tailwind/build.js:34:10)
    at Object.<anonymous> (/Users/forte/Workspace/freedom/client/tailwind/build.js:117:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by jacobp100** [comment]
Only Text elements can have a color defined, and they can't have borders
